---
# REV Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: rev-config
  namespace: rev
  labels:
    app: rev
    component: configuration
    tier: config
data:
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "structured"
  LOG_OUTPUT: "stdout"
  
  # TLS Configuration
  TLS_ENABLED: "true"
  TLS_MIN_VERSION: "1.2"
  TLS_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256"
  
  # Redis Configuration
  REDIS_URL: "redis://redis.rev.svc.cluster.local:6379/0"
  REDIS_POOL_SIZE: "10"
  REDIS_TIMEOUT: "5"
  REDIS_RETRY_ATTEMPTS: "3"
  
  # Consul Configuration (Service Discovery)
  CONSUL_URL: "http://consul.rev.svc.cluster.local:8500"
  CONSUL_PREFIX: "rev"
  CONSUL_HEALTH_CHECK_INTERVAL: "10s"
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_WINDOW: "60"
  
  # Circuit Breaker
  CIRCUIT_BREAKER_ENABLED: "true"
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  CIRCUIT_BREAKER_RESET_TIMEOUT: "60"
  
  # Health Check Configuration
  HEALTH_CHECK_TIMEOUT: "30"
  READINESS_CHECK_TIMEOUT: "10"
  STARTUP_CHECK_TIMEOUT: "60"
  
  # Performance Tuning
  WORKER_PROCESSES: "auto"
  WORKER_CONNECTIONS: "1024"
  KEEPALIVE_TIMEOUT: "65"
  CLIENT_MAX_BODY_SIZE: "10m"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  PROMETHEUS_SCRAPE_INTERVAL: "15s"
  JAEGER_SAMPLING_RATE: "0.1"
  
  # Security Headers
  SECURITY_HEADERS_ENABLED: "true"
  HSTS_MAX_AGE: "31536000"
  CONTENT_SECURITY_POLICY: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"

---
# REV Verifier Specific ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: rev-verifier-config
  namespace: rev
  labels:
    app: rev-verifier
    component: verification-engine
    tier: config
data:
  # Verifier Performance Configuration (Based on real metrics)
  MAX_MEMORY_MB: "4096"
  SEGMENT_SIZE: "512"
  BUFFER_SIZE: "4"
  CACHE_SIZE: "1000"
  
  # Model Configuration
  MODEL_CACHE_ENABLED: "true"
  MODEL_OFFLOAD_ENABLED: "true"
  MODEL_PRECISION: "fp16"
  
  # GPU Configuration
  CUDA_VISIBLE_DEVICES: "0"
  GPU_MEMORY_FRACTION: "0.8"
  GPU_ALLOW_GROWTH: "true"
  
  # Performance Targets (From real testing: 52-440MB memory, 50-200ms inference)
  TARGET_MEMORY_USAGE_MB: "440"
  TARGET_INFERENCE_TIME_MS: "200"
  MAX_INFERENCE_TIME_MS: "500"
  
  # Rate Limiting
  RATE_LIMIT_RPS: "100"
  RATE_LIMIT_BURST: "200"
  
  # Checkpointing
  CHECKPOINT_ENABLED: "true"
  CHECKPOINT_INTERVAL: "100"
  CHECKPOINT_MAX_FILES: "5"

---
# HBT Consensus Specific ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: hbt-consensus-config
  namespace: rev
  labels:
    app: hbt-consensus
    component: consensus-engine
    tier: config
data:
  # Consensus Configuration
  NUM_VALIDATORS: "5"
  FAULT_TOLERANCE: "1"
  CONSENSUS_THRESHOLD: "0.67"
  BYZANTINE_TOLERANCE: "true"
  
  # Performance Configuration
  MAX_MEMORY_MB: "8192"
  CONSENSUS_TIMEOUT: "30"
  HEARTBEAT_INTERVAL: "5"
  LEADER_ELECTION_TIMEOUT: "10"
  
  # Network Configuration
  PEER_DISCOVERY: "consul"
  PEER_DISCOVERY_INTERVAL: "30"
  CONNECTION_POOL_SIZE: "20"
  MAX_CONNECTIONS_PER_PEER: "5"
  
  # Persistence Configuration
  PERSISTENCE_ENABLED: "true"
  SYNC_WRITE: "true"
  COMPACTION_INTERVAL: "3600"
  
  # Metrics Configuration
  METRICS_DETAILED: "true"
  CONSENSUS_METRICS_ENABLED: "true"

---
# Unified Coordinator Specific ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-coordinator-config
  namespace: rev
  labels:
    app: unified-coordinator
    component: api-coordinator
    tier: config
data:
  # Coordinator Configuration
  MAX_MEMORY_MB: "2048"
  CACHE_ENABLED: "true"
  CACHE_TTL: "300"
  MODE_SELECTION: "auto"
  
  # Load Balancing
  LOAD_BALANCER_ALGORITHM: "round_robin"
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "10"
  
  # Rate Limiting
  RATE_LIMIT_RPS: "500"
  RATE_LIMIT_BURST: "1000"
  
  # Circuit Breaker
  CIRCUIT_BREAKER_THRESHOLD: "0.5"
  CIRCUIT_BREAKER_TIMEOUT: "60"
  CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS: "3"
  
  # Service URLs (Internal Kubernetes Services)
  REV_SERVICE_URL: "http://rev-verifier.rev.svc.cluster.local:8001"
  HBT_SERVICE_URL: "http://hbt-consensus.rev.svc.cluster.local:8002"
  
  # API Configuration
  API_TIMEOUT: "300"
  MAX_CONCURRENT_REQUESTS: "100"
  REQUEST_ID_HEADER: "X-Request-ID"
  
  # WebSocket Configuration
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_PING_INTERVAL: "30"
  WEBSOCKET_PONG_TIMEOUT: "60"

---
# Monitoring ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: monitoring
  labels:
    app: monitoring
    component: configuration
    tier: monitoring
data:
  # Prometheus Configuration
  PROMETHEUS_RETENTION: "30d"
  PROMETHEUS_SCRAPE_INTERVAL: "15s"
  PROMETHEUS_EVALUATION_INTERVAL: "15s"
  
  # Jaeger Configuration
  JAEGER_AGENT_HOST: "jaeger.monitoring.svc.cluster.local"
  JAEGER_AGENT_PORT: "6831"
  JAEGER_SAMPLER_TYPE: "probabilistic"
  JAEGER_SAMPLER_PARAM: "0.1"
  JAEGER_REPORTER_MAX_QUEUE_SIZE: "1000"
  
  # Grafana Configuration
  GRAFANA_ADMIN_PASSWORD: "admin"
  GRAFANA_ALLOW_SIGN_UP: "false"
  GRAFANA_AUTO_ASSIGN_ORG_ROLE: "Viewer"