global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rev-hbt-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Unified Coordinator metrics
  - job_name: 'unified-coordinator'
    static_configs:
      - targets: 
        - 'unified-coordinator:8000'
        - 'unified-coordinator:8009'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # REV Verifier metrics
  - job_name: 'rev-verifier'
    static_configs:
      - targets:
        - 'rev-verifier:8001'
        - 'rev-verifier:8002'
        - 'rev-verifier:8003'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # HBT Consensus metrics
  - job_name: 'hbt-consensus'
    static_configs:
      - targets:
        - 'hbt-consensus:8004'
        - 'hbt-consensus:8005'
        - 'hbt-consensus:8006'
        - 'hbt-consensus:8007'
        - 'hbt-consensus:8008'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 10s

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s